grails-app/domain/com/ef/app/qm/Evalanswer.groovy
package com.ef.app.qm

class Evalanswer {

	Integer evalanswerScore
	String evalanswerAnimatorComment
	String evalanswerSupComment
	String evalanswerCentraleComment
	Evaluation evaluation
	Questions questions

	static belongsTo = [Evaluation, Questions]

	static mapping = {
		id column: "EVALANSWER_ID"
		version false
	}

	static constraints = {
		evalanswerScore nullable: true
		evalanswerAnimatorComment nullable: true, maxSize: 250
		evalanswerSupComment nullable: true, maxSize: 250
		evalanswerCentraleComment nullable: true, maxSize: 250
	}
}

grails-app/controllers/com/ef/app/qm/EvalanswerController.groovy
package com.ef.app.qm

import com.ef.app.qm.Evalanswer

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class EvalanswerController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Evalanswer.list(params), model:[evalanswerInstanceCount: Evalanswer.count()]
    }

    def show(Evalanswer evalanswerInstance) {
        respond evalanswerInstance
    }

    def create() {
        respond new Evalanswer(params)
    }

    @Transactional
    def save(Evalanswer evalanswerInstance) {
        if (evalanswerInstance == null) {
            notFound()
            return
        }

        if (evalanswerInstance.hasErrors()) {
            respond evalanswerInstance.errors, view:'create'
            return
        }

        evalanswerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.type="success"
                flash.message = message(code: 'default.created.message', args: [message(code: 'evalanswer.label', default: 'com.ef.app.qm.Evalanswer'), evalanswerInstance.id])
                redirect evalanswerInstance
            }
            '*' { respond evalanswerInstance, [status: CREATED] }
        }
    }

    def edit(Evalanswer evalanswerInstance) {
        respond evalanswerInstance
    }


    def update(Evalanswer evalanswerInstance) {
        if (evalanswerInstance == null) {
            notFound()
            return
        }

        if (evalanswerInstance.hasErrors()) {
            respond evalanswerInstance.errors, view:'edit'
            return
        }

        evalanswerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.type="success"
                flash.message = message(code: 'default.updated.message', args: [message(code: 'com.ef.app.qm.Evalanswer.label', default: 'com.ef.app.qm.Evalanswer'), evalanswerInstance.id])
                redirect evalanswerInstance
            }
            '*'{ respond evalanswerInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Evalanswer evalanswerInstance) {

        if (evalanswerInstance == null) {
            notFound()
            return
        }

        evalanswerInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.type="success"
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'com.ef.app.qm.Evalanswer.label', default: 'com.ef.app.qm.Evalanswer'), evalanswerInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.type="danger"
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'evalanswer.label', default: 'com.ef.app.qm.Evalanswer'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/evalanswer/_form.gsp
<%@ page import="com.ef.app.qm.Questions; com.ef.app.qm.Evaluation" %>




<div class="fieldcontain ${hasErrors(bean: evalanswerInstance, field: 'evalanswerScore', 'error')} ">
	<label for="evalanswerScore">
		<g:message code="evalanswer.evalanswerScore.label" default="Evalanswer Score" />
		
	</label>
	<g:field name="evalanswerScore" type="number" value="${evalanswerInstance.evalanswerScore}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: evalanswerInstance, field: 'evalanswerAnimatorComment', 'error')} ">
	<label for="evalanswerAnimatorComment">
		<g:message code="evalanswer.evalanswerAnimatorComment.label" default="Evalanswer Animator Comment" />
		
	</label>
	<g:textField name="evalanswerAnimatorComment" maxlength="250" value="${evalanswerInstance?.evalanswerAnimatorComment}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: evalanswerInstance, field: 'evalanswerSupComment', 'error')} ">
	<label for="evalanswerSupComment">
		<g:message code="evalanswer.evalanswerSupComment.label" default="Evalanswer Sup Comment" />
		
	</label>
	<g:textField name="evalanswerSupComment" maxlength="250" value="${evalanswerInstance?.evalanswerSupComment}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: evalanswerInstance, field: 'evaluation', 'error')} required">
	<label for="evaluation">
		<g:message code="evalanswer.evaluation.label" default="Evaluation" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="evaluation" name="evaluation.id" from="${com.ef.app.qm.Evaluation.list()}" optionKey="id" required="" value="${evalanswerInstance?.evaluation?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: evalanswerInstance, field: 'questions', 'error')} required">
	<label for="questions">
		<g:message code="evalanswer.questions.label" default="Questions" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="questions" name="questions.id" from="${com.ef.app.qm.Questions.list()}" optionKey="id" required="" value="${evalanswerInstance?.questions?.id}" class="many-to-one"/>

</div>

grails-app/views/evalanswer/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'evalanswer.label', default: 'Evalanswer')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-evalanswer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-evalanswer" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${evalanswerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${evalanswerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:evalanswerInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/evalanswer/edit.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'evalanswer.label', default: 'Evalanswer')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-evalanswer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-evalanswer" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${evalanswerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${evalanswerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:evalanswerInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${evalanswerInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/evalanswer/index.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'evalanswer.label', default: 'Evalanswer')}" />
		<title><g:message code="com.expertflow.ma.onsiteqm.applicationName"/></title>
	</head>
	<body>
		<a href="#list-evalanswer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-evalanswer" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="evalanswerScore" title="${message(code: 'evalanswer.evalanswerScore.label', default: 'Evalanswer Score')}" />
					
						<g:sortableColumn property="evalanswerAnimatorComment" title="${message(code: 'evalanswer.evalanswerAnimatorComment.label', default: 'Evalanswer Animator Comment')}" />
					
						<g:sortableColumn property="evalanswerSupComment" title="${message(code: 'evalanswer.evalanswerSupComment.label', default: 'Evalanswer Sup Comment')}" />
					
						<th><g:message code="evalanswer.evaluation.label" default="Evaluation" /></th>
					
						<th><g:message code="evalanswer.questions.label" default="Questions" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${evalanswerInstanceList}" status="i" var="evalanswerInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${evalanswerInstance.id}">${fieldValue(bean: evalanswerInstance, field: "evalanswerScore")}</g:link></td>
					
						<td>${fieldValue(bean: evalanswerInstance, field: "evalanswerAnimatorComment")}</td>
					
						<td>${fieldValue(bean: evalanswerInstance, field: "evalanswerSupComment")}</td>

						<td>${fieldValue(bean: evalanswerInstance, field: "evaluation")}</td>
					
						<td>${fieldValue(bean: evalanswerInstance, field: "questions")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${evalanswerInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/evalanswer/show.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'evalanswer.label', default: 'Evalanswer')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-evalanswer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-evalanswer" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list evalanswer">
			
				<g:if test="${evalanswerInstance?.evalanswerScore}">
				<li class="fieldcontain">
					<span id="evalanswerScore-label" class="property-label"><g:message code="evalanswer.evalanswerScore.label" default="Evalanswer Score" /></span>
					
						<span class="property-value" aria-labelledby="evalanswerScore-label"><g:fieldValue bean="${evalanswerInstance}" field="evalanswerScore"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${evalanswerInstance?.evalanswerAnimatorComment}">
				<li class="fieldcontain">
					<span id="evalanswerAnimatorComment-label" class="property-label"><g:message code="evalanswer.evalanswerAnimatorComment.label" default="Evalanswer Animator Comment" /></span>
					
						<span class="property-value" aria-labelledby="evalanswerAnimatorComment-label"><g:fieldValue bean="${evalanswerInstance}" field="evalanswerAnimatorComment"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${evalanswerInstance?.evalanswerSupComment}">
				<li class="fieldcontain">
					<span id="evalanswerSupComment-label" class="property-label"><g:message code="evalanswer.evalanswerSupComment.label" default="Evalanswer Sup Comment" /></span>
					
						<span class="property-value" aria-labelledby="evalanswerSupComment-label"><g:fieldValue bean="${evalanswerInstance}" field="evalanswerSupComment"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${evalanswerInstance?.evaluation}">
				<li class="fieldcontain">
					<span id="evaluation-label" class="property-label"><g:message code="evalanswer.evaluation.label" default="Evaluation" /></span>
					
						<span class="property-value" aria-labelledby="evaluation-label"><g:link controller="evaluation" action="show" id="${evalanswerInstance?.evaluation?.id}">${evalanswerInstance?.evaluation?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${evalanswerInstance?.questions}">
				<li class="fieldcontain">
					<span id="questions-label" class="property-label"><g:message code="evalanswer.questions.label" default="Questions" /></span>
					
						<span class="property-value" aria-labelledby="questions-label"><g:link controller="questions" action="show" id="${evalanswerInstance?.questions?.id}">${evalanswerInstance?.questions?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:evalanswerInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${evalanswerInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>