grails-app/domain/com/ef/app/qm/Permission.groovy
package com.ef.app.qm

class Permission {
  String name
  String expression
  String description
  Boolean isManaged

  static constraints = {
    name(blank: false)
    expression(blank: false, unique: true)
    description(blank: true, maxSize: 1000)
    isManaged(default: true)
  }

  String toString() {
    return name
  }
}

grails-app/domain/com/ef/app/qm/Role.groovy
package com.ef.app.qm

class Role {
	String name
    String description
    Date dateCreated
    Date lastUpdated

    static belongsTo = [User]
    static hasMany = [members: User, permissions: String]

    static constraints = {
        name(nullable: false, blank: false, unique: true)
        description(blank: true, maxSize: 1000,nullable: true)
       /* createdBy(nullable: true)
        updatedBy(nullable: true)*/
    }

    String toString() {
        return name
    }
  
    String toFootPrintString() {
        def str = new StringBuilder("")
        
        try {
            str.append('name:'+name).append(', ')
            str.append('description:'+description).append(', ')
            str.append('dateCreated:'+dateCreated).append(', ')
            str.append('lastUpdated:'+lastUpdated).append(', ')
            str.append('members:'+members)
        }
        catch(Exception ex) {
            println 'error: '+str
            log.info 'An exception occured. ${ex.toString()}'
        }
        
        return str
    }
}

grails-app/domain/com/ef/app/qm/User.groovy
package com.ef.app.qm

class User {

	String userName
	String userPassword
	String userEmail
	String firstName
	String lastName
	boolean isActive
	Team team
	Profile profile

	static hasMany = [roles: Role, permissions: String,evaluations: Evaluation,spaces: Space]
	static belongsTo = [Profile, Team]

	static mapping = {
		table('utilisateur')
		id column: "USER_ID"
		version false
	}

	static constraints = {
		userName nullable: false
		userPassword nullable: false
		userEmail nullable: false,email: true
		team nullable: true
		profile nullable: true
	}

	String toString(){
		userName
	}
}

grails-app/controllers/com/ef/app/qm/UserController.groovy
package com.ef.app.qm

import com.ef.app.qm.Space
import com.ef.app.qm.User

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import org.apache.shiro.crypto.hash.Sha256Hash


@Transactional(readOnly = true)
class UserController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model:[userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        respond userInstance
    }

    def create() {
        respond new User(params)
    }

    @Transactional
    def save(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        def userByEmail = User.findByUserEmail(userInstance.userEmail)
        if(userByEmail != null){
            flash.type="danger"
            flash.message = message(code: 'com.ef.user.emailExiste')
            render view: 'create', model: [userInstance:userInstance]
            return
        }

        def userByUserName = User.findByUserName(userInstance.userName)
        if(userByUserName != null){
            flash.type="danger"
            flash.message = message(code: 'com.ef.user.userExiste')
            render view: 'create', model: [userInstance:userInstance]
            return
        }

        if((userInstance.profile == Profile.findByProfilNameLike("%Chef de cellule%") || userInstance.profile == Profile.findByProfilNameLike("%Animateur%")) && userInstance.team == null){
            flash.type="danger"
            flash.message = message(code: 'default.error.message')
            render view: 'create', model: [userInstance:userInstance,profile_error:"error"]
            return
        }

        if (userInstance.hasErrors()) {
            flash.type="danger"
            flash.message = message(code: 'default.error.message')
            render view: 'create', model: [userInstance:userInstance]
            return
        }

        def spaces =  params.spaces

        userInstance.userPassword =  new Sha256Hash(userInstance.userPassword).toHex()
        userInstance.addToPermissions("*:*")
        userInstance.isActive = true
        userInstance.save flush:true

        def id = userInstance.id

        if (spaces != null && !spaces.class.isArray()){
            def espace = Space.get(spaces);
            espace.user = User.get(id);
            espace.save flush:true
        }else{
            for(space in spaces){
                def espace = Space.get(space);
                espace.user = User.get(id);
                espace.save flush:true
            }
        }

        request.withFormat {
            form multipartForm {
                flash.type="success"
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), userInstance.userName])
                redirect userInstance
            }
            '*' { respond userInstance, [status: CREATED] }
        }
    }

    def edit(User userInstance) {
        respond userInstance
    }


    def update(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }

        // check userEmail Exist or not
        def userByEmail = User.findByUserEmailAndIdNotEqual(userInstance.userEmail,userInstance.id)
        if(userByEmail != null ){
            flash.type="danger"
            flash.message = message(code: 'com.ef.user.emailExiste')
            render view: 'edit', model: [userInstance:userInstance]
            return
        }
        // check userName Exist or not
        def userByUserName = User.findByUserNameAndIdNotEqual(userInstance.userName,userInstance.id)
        if(userByUserName != null ){
            flash.type="danger"
            flash.message = message(code: 'com.ef.user.userExiste')
            render view: 'edit', model: [userInstance:userInstance]
            return
        }
        // delete all spaces of the user
        def spacesOfUser = Space.findAllByUser(userInstance);
        for(sp in spacesOfUser){
            sp.user = null;
            sp.save flush:true
        }
        // add news spaces
        def spaces =  params.spaces
        def id = userInstance.id

        if (spaces != null && !spaces.class.isArray()){
            def espace = Space.get(spaces);
            espace.user = User.get(id);
            espace.save flush:true
        }else{
            for(space in spaces){
                def espace = Space.get(space);
                espace.user = User.get(id);
                espace.save flush:true
            }
        }

        if (userInstance.hasErrors()) {
            flash.type="danger"
            flash.message = message(code: 'default.error.message')
            render view: 'edit', model: [userInstance:userInstance]
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.type="success"
                flash.message = message(code: 'default.updated.message', args: [message(code: 'com.ef.app.qm.User.label', default: 'User'), userInstance.userName])
                redirect userInstance
            }
            '*'{ respond userInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }

        userInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.type="success"
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'com.ef.app.qm.User.label', default: 'User'), userInstance.userName])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.type="danger"
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/_form.gsp
<%@ page import="com.ef.app.qm.Team; com.ef.app.qm.Profile; com.ef.app.qm.Space; javax.validation.constraints.Null" %>

<div class="row form-group has-${hasErrors(bean: userInstance, field: 'userName', 'error')}">
	<div class="col-lg-2" style="font-weight: bold" >
		<g:message code="user.userName.label" default="com.ef.app.qm.User Name" />
		<span class="required-indicator" style="color:red" >*</span>
	</div>
	<div class="col-lg-3">
		<g:textField  class="form-control" name="userName" value="${userInstance?.userName}"/>
	</div>
</div>

<div class="row form-group has-${hasErrors(bean: userInstance, field: 'firstName', 'error')}">
	<div class="col-lg-2" style="font-weight: bold" >
		<g:message code="user.firstName.label" default="com.ef.app.qm.User Name" />
		<span class="required-indicator" style="color:red" >*</span>
	</div>
	<div class="col-lg-3">
		<g:textField  class="form-control" name="firstName" value="${userInstance?.firstName}"/>
	</div>
</div>

<div class="row form-group has-${hasErrors(bean: userInstance, field: 'lastName', 'error')}">
	<div class="col-lg-2" style="font-weight: bold" >
		<g:message code="user.lastName.label" default="com.ef.app.qm.User Name" />
		<span class="required-indicator" style="color:red" >*</span>
	</div>
	<div class="col-lg-3">
		<g:textField  class="form-control" name="lastName" value="${userInstance?.lastName}"/>
	</div>
</div>


<div class="row form-group has-${hasErrors(bean: userInstance, field: 'userPassword', 'error')}">
	<div class="col-lg-2" style="font-weight: bold" >
		<g:message code="user.userPassword.label" default="com.ef.app.qm.User Password" />
		<span class="required-indicator" style="color:red" >*</span>
	</div>
	<div class="col-lg-3">
		<g:passwordField  class="form-control" name="userPassword" value="${userInstance?.userPassword}"/>
	</div>
</div>

<div class="row form-group has-${hasErrors(bean: userInstance, field: 'userEmail', 'error')}">
	<div class="col-lg-2" style="font-weight: bold" >
		<g:message code="user.userEmail.label" default="com.ef.app.qm.User Email" />
		<span class="required-indicator" style="color:red" >*</span>
	</div>
	<div class="col-lg-3">
		<g:textField  class="form-control" name="userEmail" value="${userInstance?.userEmail}"/>
	</div>
</div>

<div class="row form-group ">
	<div class="col-lg-2" style="font-weight: bold" >
		<g:message code="user.profil.label" default="com.ef.app.qm.Profile" />
	</div>
	<div class="col-lg-3">
		<g:select value="${userInstance?.profile?.id}" class="form-control" id="profile" name="profile.id" from="${com.ef.app.qm.Profile.list()}" optionKey="id" optionValue="profilName" />
	</div>
</div>

<div class="row profileAdmin form-group has-${(profile_error == null)?'':profile_error}">
	<div class="col-lg-2" style="font-weight: bold" >
		<g:message code="user.team.label" default="com.ef.app.qm.Team" />
		<span class="required-indicator" style="color:red" >*</span>
	</div>
	<div class="col-lg-3">
		<g:select value="${userInstance?.team?.id}" class="form-control" id="team" name="team.id" from="${com.ef.app.qm.Team.list()}" noSelection="${['null':'']}" optionKey="id" optionValue="teamName" />
	</div>
</div>

<g:if test="${userInstance?.id == null}">
	<div class="row form-group profileAdmin ">
		<div class="col-lg-2" style="font-weight: bold" >
			<g:message code="user.space.label" default="com.ef.app.qm.Team" />
		</div>
		<div class="col-lg-3 ">
			<p style="  height: 100px;overflow-y: scroll;border: 1pt solid #ccc;border-radius: 3pt;padding: 5px;">
				<g:each var="space" in="${com.ef.app.qm.Space.findAllByUser(null)}">
					<label><input style="vertical-align: top;" type="checkbox" name="spaces" value="${space.id}" />&nbsp;${space.spaceName}</label><br>
				</g:each>
			</p>
		</div>
	</div>
</g:if>
<g:else>
	<div class="row form-group profileAdmin ">
		<div class="col-lg-2" style="font-weight: bold" >
			<g:message code="user.space.label" default="com.ef.app.qm.Team" />
		</div>
		<div class="col-lg-3 ">
			<p style="  height: 100px;overflow-y: scroll;border: 1pt solid #ccc;border-radius: 3pt;padding: 5px;">
				<g:each var="space" in="${Space.findAllByUserOrUser(userInstance,null)}">
					<g:if test="${space?.user == null}">
						<label><input style="vertical-align: top;" type="checkbox" name="spaces" value="${space.id}" />&nbsp;${space.spaceName}</label><br>
					</g:if>
					<g:else>
						<label><input checked="checked" style="vertical-align: top;" type="checkbox" name="spaces" value="${space.id}" />&nbsp;${space.spaceName}</label><br>
					</g:else>
				</g:each>
			</p>
		</div>
	</div>
</g:else>

grails-app/views/user/viewpermissions.gsp
<%@ page import="org.apache.shiro.SecurityUtils" %>


<%--
  Author: Akeel
  Date: 12/20/12
  Time: 12:20 AM
--%>

<!doctype html>
<html>
<head>
    <meta name="layout" content="qm_main"/>
    <g:set var="userEntity" value="${message(code: 'com.ef.qm.entity.user', default: 'User')}"/>
    <g:set var="roleEntity" value="${message(code: 'com.ef.qm.entity.role', default: 'Role')}"/>
    <g:set var="permissionEntity" value="${message(code: 'com.ef.qm.entity.permission', default: 'Permission')}"/>
    <title><g:message code="cbr.form.permissionsAssignedTo.label" args="[userInstance.username]" default="Assign permission"/></title>
</head>

<body>
    <div class="row">
        <div class="col-lg-3">
            <g:render template="/templates/usermanagement" />
        </div>

        <div class="col-lg-9">
            
            <div class="page-header">
                <h1><g:message code="cbr.form.permissionsAssignedTo.label" args="[userInstance.username]" default="Assign Permission to ${userInstance?.username}"/></h1>
            </div>

            <div class="tab  tabs-left">
                <ul class="nav nav-tabs">                    
                    <li class="${params.tab=='current' ? 'active' : ''}">
                        <g:link action="viewpermissions" id="${userInstance.id}" params="[tab:'current']">
                            ${message(code:'com.ef.qm.currentPermissions.label',default: "Current Permissions")}
                        </g:link>
                    </li>
                    <li class="${params.tab=='assign' ? 'active' : ''}">
                        <g:link action="viewpermissions" id="${userInstance.id}" params="[tab:'assign']">
                            ${message(code:'com.ef.qm.assignPermissions.label',default: "Assign Permissions")}
                        </g:link>
                    </li>
                    <li class="${params.tab=='rolePermission' ? 'active' : ''}">
                        <g:link action="viewpermissions" id="${userInstance.id}" params="[tab:'rolePermission']">
                            ${message(code:'com.ef.qm.roleUserPermissions.label',default: "Permissions from rules")}
                        </g:link>
                    </li>

                </ul>
                <div class="tab-content">
                    <div class="tab-pane ${params.tab=='current' ? 'active' : ''}" id="current">
                        <table class="table table-striped table-bordered table-condensed mytable">
                            <thead>
                                <tr>
                                    <th>${message(code: 'com.ef.qm.label.name',default: "Name")}</th>
                                    <th>${message(code: 'com.ef.qm.label.description',default: "Description")}</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <g:each in="${userPermissionList}" status="i" var="userPermission">
                                    <tr>
                                        <td><g:message code="${userPermission?.name}"/> </td>
                                        <td><g:message code="${userPermission?.description}"/> </td>

                                        <td width="20%">
                                            <g:if test="${SecurityUtils.subject.isPermitted('user:reovkepermission')}">
                                                <g:link action="reovkepermission" class="btn btn-xs btn-info" id="${userPermission?.id}" params="[uid:userInstance.id, tab:'current']">
                                                    <g:message code="com.ef.qm.label.revokePermission" default="Revoke permissions"/>
                                                </g:link>
                                            </g:if>
                                            <g:else>
                                                <g:link class="btn btn-xs" disabled="disabled">
                                                    <g:message code="com.ef.qm.label.revokePermission" default="Revoke permissions"/>
                                                </g:link>
                                            </g:else>
                                        </td>
                                    </tr>
                                </g:each>
                            </tbody>
                        </table>
                        %{--<div class="pull-right">
                            <bootstrap:paginate  total="${userPermissionTotal}" id="${userInstance.id}" params="[tab:'current']" />
                            </div>--}%
                    </div>
                    <div class="tab-pane ${params.tab=='assign' ? 'active' : ''}" id="assign">
                        <table class="table table-striped table-bordered table-condensed mytable" >
                            <thead>
                                <tr>
                                    <g:sortableColumn property="name" title="${message(code: 'com.ef.qm.label.name',default: "Name")}"/>
                                    <th>${message(code: 'com.ef.cbr.label.description',default: "Description")}</th>
                                     <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <g:each in="${permissionList}" var="permission">
                                    <tr>
                                        <td><g:message code="${permission?.name}"/> </td>
                                        <td><g:message code="${permission?.description}"/> </td>
                                        <td width="20%">
                                            <g:if test="${SecurityUtils.subject.isPermitted('user:assignpermission')}">
                                                <g:link action="assignpermission" class="btn btn-xs btn-info" id="${permission.id}" params="[uid:userInstance.id, tab:'assign']">
                                                    <g:message code="com.ef.qm.label.assignPermission" default="Assign Permission"/>
                                                </g:link>
                                            </g:if>
                                            <g:else>
                                                <g:link class="btn btn-xs btn-info" disabled="disabled">
                                                    <g:message code="com.ef.qm.label.assignPermission" default="Assign Permission"/>
                                                </g:link>
                                            </g:else>
                                        </td>
                                    </tr>
                                </g:each>
                            </tbody>
                        </table>
                        %{--<div class="pull-right">--}%
                            %{--<bootstrap:paginate   total="${permissionTotal}" id="${userInstance.id}" params="[tab:'assign']" />--}%
                        %{--</div>--}%
                    </div>
                    <div class="tab-pane ${params.tab=='rolePermission' ? 'active' : ''}" id="rolePermission">
                        <table class="table table-striped table-bordered table-condensed mytable" >
                            <thead>
                            <tr>
                                <g:sortableColumn property="name" title="${message(code: 'com.ef.qm.label.name',default: "Name")}"/>
                                <th>${message(code: 'com.ef.qm.label.description',default: "Description")}</th>

                            </tr>
                            </thead>
                            <tbody>
                            <g:each in="${roleUserPermission}" var="permission">
                                <tr>
                                    <td><g:message code="${permission?.name}"/> </td>
                                    <td><g:message code="${permission?.description}"/> </td>
                                    %{--<td width="20%" class="hidden">
                                        <g:if test="${SecurityUtils.subject.isPermitted('user:assignpermission')}">
                                            <g:link action="assignpermission" class="btn btn-xs btn-info" id="${permission.id}" params="[uid:userInstance.id, tab:'assign']">
                                                <g:message code="com.ef.cbr.label.assignPermission"/>
                                            </g:link>
                                        </g:if>
                                        <g:else>
                                            <g:link class="btn btn-xs btn-info" disabled="disabled">
                                                <g:message code="com.ef.cbr.label.assignPermission"/>
                                            </g:link>
                                        </g:else>
                                    </td>--}%
                                </tr>
                            </g:each>
                            </tbody>
                        </table>
                        %{--<div class="pull-right">--}%
                        %{--<bootstrap:paginate   total="${permissionTotal}" id="${userInstance.id}" params="[tab:'assign']" />--}%
                        %{--</div>--}%
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script>
    var myParam = location.search.split('lang=')[1] ? location.search.split('lang=')[1] : 'en';;
    $('.mytable').dataTable({
        "bInfo": false,
        "bAutoWidth": false,
        "oLanguage": {
            "sUrl": "../../dataTableLang/dataTables_"+myParam+".txt"
        }
    });

</script>

grails-app/views/user/viewroles.gsp
<%@ page import="org.apache.shiro.SecurityUtils" %>

<%--
  Author: Akeel
  Date: 12/20/12
  Time: 12:20 AM
--%>

<!doctype html>
<html>
<head>
    <meta name="layout" content="qm_main"/>
    <g:set var="userEntity" value="${message(code: 'com.ef.qm.entity.user', default: 'User')}"/>
    <g:set var="roleEntity" value="${message(code: 'com.ef.qm.entity.role', default: 'Role')}"/>
    <g:set var="permissionEntity" value="${message(code: 'com.ef.qm.entity.permission', default: 'Permission')}"/>
    <title><g:message code="cbr.form.rolesAssignedTo.label" args="[userInstance.userName]" default="Roles assigned to ${userInstance?.username}"/></title>
</head>

<body>
    <div class="row">
        <div class="col-lg-3">
            <g:render template="/templates/usermanagement" />
        </div>

        <div class="col-lg-9">
            
            <div class="page-header">
                <h1><g:message code="cbr.form.rolesAssignedTo.label" args="[userInstance.username]" default="Roles assigned to ${userInstance?.username}"/></h1>
            </div>

            <div class="tabbable tabs-left">
                <ul class="nav nav-tabs">
                    <li class="${params.tab=='current' ? 'active' : ''}">
                        <g:link action="viewroles" id="${userInstance.id}"  params="[tab:'current']">
                            ${message(code:'cbr.form.tabs.currentRoles.label',default: "Current roles")}
                        </g:link>
                    </li>
                    <li class="${params.tab=='assign' ? 'active' : ''}">
                        <g:link action="viewroles" id="${userInstance.id}"  params="[tab:'assign']">
                            ${message(code:'cbr.form.tabs.addMoreRoles.label',default: "Add roles")}
                        </g:link>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane ${params.tab=='current' ? 'active' : ''}" id="current">
                        <table class="table table-striped table-bordered table-condensed mytable" >
                            <thead>
                                <tr>
                                    <th>${message(code: 'com.ef.qm.label.name',default: "Name")}</th>
                                    <th>${message(code: 'com.ef.qm.label.description',default: "Description")}</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <g:each in="${userRoleList}" var="role">
                                    <tr>
                                        <td>
                                            <g:link controller="role" action="show" id="${role.id}">${role?.name}</g:link>
                                        </td>
                                        <td>${role?.description}</td>
                                        <td width="20%">
                                            <g:if test="${SecurityUtils.subject.isPermitted('user:reovkerole')}">
                                                <g:link action="revokerole" class="btn btn-xs btn-info" id="${role?.id}" params="[uid:userInstance.id, tab:'current']">
                                                    <g:message code="com.ef.qm.label.revokeRole" default="Revoke Rules"/>
                                                </g:link>
                                            </g:if>
                                            <g:else>
                                                <g:link class="btn btn-xs" disabled="disabled">
                                                    <g:message code="com.ef.qm.label.revokeRole" default="Revoke Rules"/>
                                                </g:link>
                                            </g:else>
                                        </td>
                                    </tr>
                                </g:each>
                            </tbody>
                        </table>
                       %{-- <div class=" pull-right">
                            <bootstrap:paginate  total="${userRoleTotal}" id="${userInstance.id}" params="[tab:'current']"/>
                        </div>--}%
                    </div>
                    <div class="tab-pane ${params.tab=='assign' ? 'active' : ''}" id="assign">
                        <table class="table table-striped table-bordered table-condensed mytable">
                            <thead>
                                <tr>
                                    <g:sortableColumn property="name" title="${message(code: 'com.ef.qm.label.name',default: "Name")}"/>
                                    <th>${message(code: 'com.ef.qm.label.description',default: "Description")}</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <g:each in="${roleList}" var="role">
                                    <tr>
                                        <td>
                                            <g:link controller="role" action="show" id="${role.id}">${role?.name}</g:link>
                                        </td>
                                        <td>${role?.description}</td>
                                        <td width="20%">
                                            <g:if test="${SecurityUtils.subject.isPermitted('user:assignrole')}">
                                                <g:link action="assignrole" class="btn btn-xs btn-info" id="${role?.id}" params="[uid:userInstance.id, tab:'assign']">
                                                    <g:message code="com.ef.qm.label.assignRole" default="Assign role"/>
                                                </g:link>
                                            </g:if>
                                            <g:else>
                                                <g:link class="btn btn-xs btn-info" disabled="disabled">
                                                    <g:message code="com.ef.qm.label.assignRole" default="Assign role"/>
                                                </g:link>
                                            </g:else>
                                        </td>
                                    </tr>
                                </g:each>
                            </tbody>
                        </table>
                        %{--<div class=" pull-right">
                            <bootstrap:paginate  total="${roleTotal}" id="${userInstance.id}" params="[tab:'assign']" />
                        </div> --}%
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

<script>
    var myParam = location.search.split('lang=')[1] ? location.search.split('lang=')[1] : 'en';;
    $('.mytable').dataTable({
        "bInfo": false,
        "bAutoWidth": false,
        "oLanguage": {
            "sUrl": "../../dataTableLang/dataTables_"+myParam+".txt"
        }
    });

</script>