grails-app/domain/com/ef/app/qm/Permission.groovy
package com.ef.app.qm

class Permission {
  String name
  String expression
  String description
  Boolean isManaged

  static constraints = {
    name(blank: false)
    expression(blank: false, unique: true)
    description(blank: true, maxSize: 1000)
    isManaged(default: true)
  }

  String toString() {
    return name
  }
}

grails-app/domain/com/ef/app/qm/Role.groovy
package com.ef.app.qm

class Role {
	String name
    String description
    Date dateCreated
    Date lastUpdated

    static belongsTo = [User]
    static hasMany = [members: User, permissions: String]

    static constraints = {
        name(nullable: false, blank: false, unique: true)
        description(blank: true, maxSize: 1000,nullable: true)
       /* createdBy(nullable: true)
        updatedBy(nullable: true)*/
    }

    String toString() {
        return name
    }
  
    String toFootPrintString() {
        def str = new StringBuilder("")
        
        try {
            str.append('name:'+name).append(', ')
            str.append('description:'+description).append(', ')
            str.append('dateCreated:'+dateCreated).append(', ')
            str.append('lastUpdated:'+lastUpdated).append(', ')
            str.append('members:'+members)
        }
        catch(Exception ex) {
            println 'error: '+str
            log.info 'An exception occured. ${ex.toString()}'
        }
        
        return str
    }
}

grails-app/controllers/com/ef/app/qm/PermissionController.groovy
package com.ef.app.qm

import org.springframework.dao.DataIntegrityViolationException

class PermissionController {

    static allowedMethods = [create: ['GET', 'POST'], edit: ['GET', 'POST'], delete: 'GET']

    def index() {
        redirect action: 'list', params: params
    }

    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [permissionInstanceList: Permission.list(), permissionInstanceTotal: Permission.count(),controllerName:'listPermi']
    }

    def create() {
		switch (request.method) {
		case 'GET':
        	[permissionInstance: new Permission(params),controllerName:'listPermi']
			break
		case 'POST':
	        def permissionInstance = new Permission(params)
	        if (!permissionInstance.save(flush: true)) {
	            render view: 'create', model: [permissionInstance: permissionInstance,controllerName:'listPermi']
	            return
	        }

			flash.message = message(code: 'default.created.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), permissionInstance.name])
	        flash.type="success"
	        redirect action: 'list'
			break
		}
    }
    def createModal() {
        switch (request.method) {
            case 'GET':
                render template:'modalCreate',model:[permissionInstance: new Permission(params),controllerName:'listPermi']
                break
            case 'POST':
                def permissionInstance = new Permission(params)
                if (!permissionInstance.save(flush: true)) {
                    render view: 'create', model: [permissionInstance: permissionInstance,controllerName:'listPermi']
                    return
                }

                flash.message = message(code: 'default.created.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), permissionInstance.name])
                flash.type="success"
                redirect action: 'list'
                break
        }
    }
    def show() {
        def permissionInstance = Permission.get(params.id)
        if (!permissionInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), params.id])
            flash.type="danger"
            redirect action: 'list'
            return
        }

        [permissionInstance: permissionInstance,controllerName: 'listPermi']
    }

    def edit() {
		switch (request.method) {
		case 'GET':
	        def permissionInstance = Permission.get(params.id)
	        if (!permissionInstance) {
	            flash.message = message(code: 'default.not.found.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), params.id])
	            flash.type="danger"
	            redirect action: 'list'
	            return
	        }

	        [permissionInstance: permissionInstance,controllerName: 'listPermi']
			break
		case 'POST':
	        def permissionInstance = Permission.get(params.id)
	        if (!permissionInstance) {
	            flash.message = message(code: 'default.not.found.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), params.id])
	            flash.type="danger"
	            redirect action: 'list'
	            return
	        }

	        if (params.version) {
	            def version = params.version.toLong()
	            if (permissionInstance.version > version) {
	                permissionInstance.errors.rejectValue('version', 'default.optimistic.locking.failure',
	                          [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission')] as Object[],
	                          "Another user has updated this com.ef.app.qm.Permission while you were editing")
	                render view: 'edit', model: [permissionInstance: permissionInstance]
	                return
	            }
	        }

	        permissionInstance.properties = params

	        if (!permissionInstance.save(flush: true)) {
	            render view: 'edit', model: [permissionInstance: permissionInstance]
	            return
	        }

			flash.message = message(code: 'default.updated.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), permissionInstance.name])
	        flash.type="success"
	        redirect action: 'list'
			break
		}
    }
    def editModal() {
        switch (request.method) {
            case 'GET':
                def permissionInstance = Permission.get(params.id)
                if (!permissionInstance) {
                    flash.message = message(code: 'default.not.found.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), params.id])
                    flash.type="danger"
                    redirect action: 'list'
                    return
                }

                render(template: 'modalEdit' ,model: [permissionInstance: permissionInstance,controllerName: 'listPermi'] )
                break
            case 'POST':
                def permissionInstance = Permission.get(params.id)
                if (!permissionInstance) {
                    flash.message = message(code: 'default.not.found.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), params.id])
                    flash.type="danger"
                    redirect action: 'list'
                    return
                }

                if (params.version) {
                    def version = params.version.toLong()
                    if (permissionInstance.version > version) {
                        permissionInstance.errors.rejectValue('version', 'default.optimistic.locking.failure',
                                [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission')] as Object[],
                                "Another user has updated this com.ef.app.qm.Permission while you were editing")
                        render view: 'edit', model: [permissionInstance: permissionInstance]
                        return
                    }
                }

                permissionInstance.properties = params

                if (!permissionInstance.save(flush: true)) {
                    render view: 'edit', model: [permissionInstance: permissionInstance]
                    return
                }

                flash.message = message(code: 'default.updated.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), permissionInstance.name])
                flash.type="success"
                redirect action: 'list'
                break
        }
    }
    def delete() {
        def permissionInstance = Permission.get(params.id)
        if (!permissionInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), params.id])
            flash.type="danger"
            redirect action: 'list'
            return
        }

        try {
            permissionInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), params.id])
            flash.type="success"
            redirect action: 'list'
        }
        catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'com.ef.cbr.entity.permission', default: 'com.ef.app.qm.Permission'), params.id])
            flash.type="danger"
            redirect action: 'show', id: params.id
        }
    }

    def addAllPermission(){

        Permission.deleteAll(Permission.getAll())
        if(Permission.count == 0){
            println "Permissions not exist"
            new Permission(isManaged: true, expression: '*:*', name: 'com.ef.cbr.bootstrap.all',
                    description: 'com.ef.cbr.bootstrap.all.permission.Admin').save()
            new Permission(isManaged: true, expression: 'settings:*', name: 'com.ef.cbr.bootstrap.config',
                    description: 'com.ef.cbr.bootstrap.config.parameter').save()

            println "user Permissions"
            // com.ef.app.qm.User related Permissions
            new Permission(isManaged: true, expression: 'user:*', name: 'com.ef.cbr.bootstrap.all.user.name',
                    description: 'com.ef.cbr.bootstrap.all.user').save()
            new Permission(isManaged: true, expression: 'user:show', name: 'com.ef.cbr.bootstrap.show.user.name',
                    description: 'com.ef.cbr.bootstrap.show.user').save()
            new Permission(isManaged: true, expression: 'user:create,createForModal,save', name: 'com.ef.cbr.bootstrap.create.user.name',
                    description: 'com.ef.cbr.bootstrap.create.user').save()
            new Permission(isManaged: true, expression: 'user:edit,editpop,update', name: 'com.ef.cbr.bootstrap.edit.user.name',
                    description: 'com.ef.cbr.bootstrap.edit.user').save()
            new Permission(isManaged: true, expression: 'user:list', name: 'com.ef.cbr.bootstrap.list.user.name',
                    description: 'com.ef.cbr.bootstrap.list.user').save()
            new Permission(isManaged: true, expression: 'user:delete', name: 'com.ef.cbr.bootstrap.delete.user.name',
                    description: 'com.ef.cbr.bootstrap.delete.user').save()
            new Permission(isManaged: true, expression: 'user:activateuser', name: 'com.ef.cbr.bootstrap.activate.user.name',
                    description: 'com.ef.cbr.bootstrap.activate.user').save()
            new Permission(isManaged: true, expression: 'user:blockuser', name: 'com.ef.cbr.bootstrap.block.user.name',

grails-app/views/permission/_modalCreate.gsp
<%@ page import="com.ef.app.qm.User; org.apache.shiro.SecurityUtils;" %>
<g:set var="loggedUser" value="${com.ef.app.qm.User.findByUserName(SecurityUtils.getSubject().getPrincipal())}"/>
<g:set var="userEntity" value="${message(code: 'com.ef.qm.entity.user', default: 'User')}"/>
<g:set var="roleEntity" value="${message(code: 'com.ef.qm.entity.role', default: 'Role')}"/>
<g:set var="permissionEntity" value="${message(code: 'com.ef.qm.entity.permission', default: 'Permission')}"/>
<div class="modal-header">
    <h1><g:message code="default.create.label" args="[permissionEntity]" /></h1>
</div>
<div class="modal-body">
    <g:form class="form-horizontal" action="create">
        <fieldset>
            <g:hiddenField name="createdBy.id" value="${loggedUser.id}"/>
            <g:hiddenField name="updatedBy.id" value="${loggedUser.id}"/>
            <g:hiddenField name="isManaged" value="false"/>

            <div class="form-group ${hasErrors(bean:permissionInstance,field:'name','error')}">
                <label class="col-lg-4 control-label"   for="name">
                    <g:message code="com.qm.cbr.label.name" default="Name"/>
                    <span class="required-indicator">*</span>
                </label>
                <div class="col-lg-6">
                    <input class="form-control"class="form-control"type="text" name="name" value="${permissionInstance?.name}" required="required">
                    <span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'name')}</span>
                </div>
            </div>

            <div class="form-group ${hasErrors(bean:permissionInstance,field:'expression','error')}">
                <label class="col-lg-4 control-label"   for="expression">
                    <g:message code="com.ef.qm.label.expression" default="Expression"/>
                </label>
                <div class="col-lg-6">
                    <input class="form-control"class="form-control"type="text" name="expression" value="${permissionInstance?.expression}"
                           required="required"  class="formPopover"
                           data-content="${message(code: 'cbr.form.create.expression.hint')}"
                           placeholder="${message(code: 'cbr.form.create.expression.default')}">
                    <span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'expression')}</span>
                </div>
            </div>

            <div class="form-group ${hasErrors(bean:permissionInstance,field:'description','error')}">
                <label class="col-lg-4 control-label"   for="description">
                    <g:message code="com.ef.cbr.label.description"/>
                </label>
                <div class="col-lg-6">
                    <textarea class="form-control" name="description" rows="3" >${permissionInstance?.description}</textarea>
                    <span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'description')}</span>
                </div>
            </div>

            <div class="modal-footer row">
                <shiro:hasPermission permission="permission:list">
                    <g:link action="list" class="btn btn-default">
                        <i class="glyphicon glyphicon-circle-arrow-left"></i>
                        <g:message code="cbr.form.cancel.label"/>
                    </g:link>
                </shiro:hasPermission>
                <button type="submit" class="btn btn-primary">
                    <i class="glyphicon glyphicon-pencil glyphicon glyphicon-white"></i>
                    <g:message code="default.button.create.label" default="Create" />
                </button>
            </div>

        </fieldset>
    </g:form>

</div>

grails-app/views/permission/_modalEdit.gsp
<%@ page import="com.ef.app.qm.User; org.apache.shiro.SecurityUtils" %>
<g:set var="loggedUser" value="${com.ef.app.qm.User.findByUserName(SecurityUtils.getSubject().getPrincipal())}"/>
<g:set var="userEntity" value="${message(code: 'com.ef.cbr.entity.user', default: 'User')}"/>
<g:set var="roleEntity" value="${message(code: 'com.ef.cbr.entity.role', default: 'Role')}"/>
<g:set var="permissionEntity" value="${message(code: 'com.ef.cbr.entity.permission', default: 'Permission')}"/>
<div class="modal-header">

</div>
<div class="modal-body">
    <g:form class="form-horizontal" action="edit">
        <fieldset>
            <g:hiddenField name="createdBy.id" value="${loggedUser.id}"/>
            <g:hiddenField name="updatedBy.id" value="${loggedUser.id}"/>
            <g:hiddenField name="version" value="${permissionInstance?.version}"/>
            <g:hiddenField name="id" value="${permissionInstance.id}"/>
            <g:hiddenField name="isManaged" value="false"/>

            <div class="form-group ${hasErrors(bean:permissionInstance,field:'name','error')}">
                <label class="col-lg-4 control-label"   for="name">
                    <g:message code="com.ef.cbr.label.name"/>
                    <span class="required-indicator">*</span>
                </label>
                <div class="col-lg-6">
                    <input class="form-control"class="form-control"type="text" name="name" value="${permissionInstance?.name}" required="required">
                    <span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'name')}</span>
                </div>
            </div>

            <div class="form-group ${hasErrors(bean:permissionInstance,field:'expression','error')}">
                <label class="col-lg-4 control-label"   for="expression">
                    <g:message code="com.ef.cbr.label.expression"/>
                </label>
                <div class="col-lg-6">
                    <input class="form-control"class="form-control"type="text" name="expression" value="${permissionInstance?.expression}"
                           required="required"  class="formPopover"
                           data-content="${message(code: 'cbr.form.create.expression.hint')}"
                           placeholder="${message(code: 'cbr.form.create.expression.default')}">
                    <span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'expression')}</span>
                </div>
            </div>

            <div class="form-group ${hasErrors(bean:permissionInstance,field:'description','error')}">
                <label class="col-lg-4 control-label"   for="description">
                    <g:message code="com.ef.cbr.label.description"/>
                </label>
                <div class="col-lg-6">
                    <textarea class="form-control" name="description" rows="3" >${permissionInstance?.description}</textarea>
                    <span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'description')}</span>
                </div>
            </div>

            <div class="modal-footer row">
                <shiro:hasPermission permission="permission:list">
                    <g:link action="list" class="btn btn-default">
                        <i class="glyphicon glyphicon-circle-arrow-left"></i>
                        <g:message code="cbr.form.cancel.label"/>
                    </g:link>
                </shiro:hasPermission>
                <shiro:hasPermission permission="permission:delete">
                    <button type="submit" class="btn btn-danger confirmDelete">
                        <i class="glyphicon glyphicon-trash glyphicon glyphicon-white"></i>
                        <g:message code="default.button.delete.label" default="Delete" />
                    </button>
                </shiro:hasPermission>
                <button type="submit" class="btn btn-primary">
                    <i class="glyphicon glyphicon-pencil glyphicon glyphicon-white"></i>
                    <g:message code="default.button.update.label" default="Update" />
                </button>
            </div>

        </fieldset>
    </g:form>
</div>

grails-app/views/permission/create.gsp
<%@ page import="com.ef.app.qm.User; org.apache.shiro.SecurityUtils" %>

<%--
  Author: Akeel
  Date: 12/20/12
  Time: 1:32 AM
--%>

<!doctype html>
<html>
<head>
  	<meta name="layout" content="layoutContent"/>
  	<g:set var="loggedUser" value="${com.ef.app.qm.User.findByUserName(SecurityUtils.getSubject().getPrincipal())}"/>
  	<g:set var="userEntity" value="${message(code: 'com.ef.cbr.entity.user', default: 'User')}"/>
  	<g:set var="roleEntity" value="${message(code: 'com.ef.cbr.entity.role', default: 'Role')}"/>
  	<g:set var="permissionEntity" value="${message(code: 'com.ef.cbr.entity.permission', default: 'Permission')}"/> 
  	<title><g:message code="default.create.label" args="[permissionEntity]"/></title>
</head>

<body>
	<div class="row">
		<div class="col-lg-3">
			<g:render template="/templates/usermanagement" />
		</div>
			
		<div class="col-lg-9">
			<div class="page-header">
				<h1><g:message code="default.create.label" args="[permissionEntity]" /></h1>
			</div>
			
			<g:form class="form-horizontal" action="create">
				<fieldset>
					<g:hiddenField name="createdBy.id" value="${loggedUser.id}"/>
   					<g:hiddenField name="updatedBy.id" value="${loggedUser.id}"/>
   					<g:hiddenField name="isManaged" value="false"/>
				    
				    <div class="form-group ${hasErrors(bean:permissionInstance,field:'name','error')}">
						<label class="col-lg-4 control-label"   for="name">
							<g:message code="com.ef.cbr.label.name"/>
						</label>
						<div class="col-lg-6">
							<input class="form-control"class="form-control"type="text" name="name" value="${permissionInstance?.name}" required="required">
							<span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'name')}</span>
						</div>
					</div>

					<div class="form-group ${hasErrors(bean:permissionInstance,field:'expression','error')}">
						<label class="col-lg-4 control-label"   for="expression">
							<g:message code="com.ef.cbr.label.expression"/>
						</label>
						<div class="col-lg-6">
							<input class="form-control"class="form-control"type="text" name="expression" value="${permissionInstance?.expression}"
								   required="required"  class="formPopover"
								   data-content="${message(code: 'cbr.form.create.expression.hint')}"
								   placeholder="${message(code: 'cbr.form.create.expression.default')}">
							<span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'expression')}</span>
						</div>
					</div>
					
					<div class="form-group ${hasErrors(bean:permissionInstance,field:'description','error')}">
                        <label class="col-lg-4 control-label"   for="description">
                            <g:message code="com.ef.cbr.label.description"/>
                        </label>
                        <div class="col-lg-6">
                            <textarea class="form-control" name="description" rows="3" >${permissionInstance?.description}</textarea>
                            <span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'description')}</span>
                        </div>                          
                    </div>
   
					<div class="form-actions">
						<shiro:hasPermission permission="permission:list">
							<g:link action="list" class="btn btn-default">
								<i class="glyphicon glyphicon-circle-arrow-left"></i>
								<g:message code="cbr.form.cancel.label"/>
							</g:link>
						</shiro:hasPermission>
						<button type="submit" class="btn btn-primary">
							<i class="glyphicon glyphicon-pencil glyphicon glyphicon-white"></i>
							<g:message code="default.button.create.label" default="Create" />
						</button>
					</div>

				</fieldset>
			</g:form>
		</div>
	</div>
</body>
</html>

grails-app/views/permission/edit.gsp
<%@ page import="com.ef.app.qm.User; org.apache.shiro.SecurityUtils" %>

<%--
  Author: Akeel
  Date: 12/20/12
  Time: 1:32 AM
--%>

<!doctype html>
<html>
<head>
  	<meta name="layout" content="layoutContent"/>
  	<g:set var="loggedUser" value="${com.ef.app.qm.User.findByUserName(SecurityUtils.getSubject().getPrincipal())}"/>
  	<g:set var="userEntity" value="${message(code: 'com.ef.cbr.entity.user', default: 'User')}"/>
  	<g:set var="roleEntity" value="${message(code: 'com.ef.cbr.entity.role', default: 'Role')}"/>
  	<g:set var="permissionEntity" value="${message(code: 'com.ef.cbr.entity.permission', default: 'Permission')}"/> 
  	<title><g:message code="default.edit.label" args="[permissionEntity]"/></title>
</head>

<body>
	<div class="row">
		<div class="col-lg-3">
			<g:render template="/templates/usermanagement" />
		</div>
			
		<div class="col-lg-9">
			<div class="page-header">
				<h1><g:message code="default.edit.label" args="[permissionEntity]" /></h1>
			</div>
			
			<g:form class="form-horizontal" action="edit">
				<fieldset>
					<g:hiddenField name="createdBy.id" value="${loggedUser.id}"/>
   					<g:hiddenField name="updatedBy.id" value="${loggedUser.id}"/>
   					<g:hiddenField name="version" value="${roleInstance?.version}"/>
   					<g:hiddenField name="id" value="${permissionInstance.id}"/>
   					<g:hiddenField name="isManaged" value="false"/>
				    
				    <div class="form-group ${hasErrors(bean:permissionInstance,field:'name','error')}">
						<label class="col-lg-4 control-label"   for="name">
							<g:message code="com.ef.cbr.label.name"/>
						</label>
						<div class="col-lg-6">
							<input class="form-control"class="form-control"type="text" name="name" value="${permissionInstance?.name}" required="required">
							<span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'name')}</span>
						</div>
					</div>

					<div class="form-group ${hasErrors(bean:permissionInstance,field:'expression','error')}">
						<label class="col-lg-4 control-label"   for="expression">
							<g:message code="com.ef.cbr.label.expression"/>
						</label>
						<div class="col-lg-6">
							<input class="form-control"class="form-control"type="text" name="expression" value="${permissionInstance?.expression}"
								   required="required"  class="formPopover"
								   data-content="${message(code: 'cbr.form.create.expression.hint')}"
								   placeholder="${message(code: 'cbr.form.create.expression.default')}">
							<span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'expression')}</span>
						</div>
					</div>
					
					<div class="form-group ${hasErrors(bean:permissionInstance,field:'description','error')}">
                        <label class="col-lg-4 control-label"   for="description">
                            <g:message code="com.ef.cbr.label.description"/>
                        </label>
                        <div class="col-lg-6">
                            <textarea class="form-control" name="description" rows="3" >${permissionInstance?.description}</textarea>
                            <span class="help-inline label label-danger">${fieldError(bean:permissionInstance,field:'description')}</span>
                        </div>                          
                    </div>
   
					<div class="form-actions">
						<shiro:hasPermission permission="permission:list">
							<g:link action="list" class="btn btn-default">
								<i class="glyphicon glyphicon-circle-arrow-left"></i>
								<g:message code="cbr.form.cancel.label"/>
							</g:link>
						</shiro:hasPermission>
						<shiro:hasPermission permission="permission:delete">
							<button type="submit" class="btn btn-danger confirmDelete">
								<i class="glyphicon glyphicon-trash glyphicon glyphicon-white"></i>
								<g:message code="default.button.delete.label" default="Delete" />
							</button>
						</shiro:hasPermission>
						<button type="submit" class="btn btn-primary">
							<i class="glyphicon glyphicon-pencil glyphicon glyphicon-white"></i>
							<g:message code="default.button.update.label" default="Update" />
						</button>
					</div>

				</fieldset>
			</g:form>
		</div>
	</div>
</body>
</html>

grails-app/views/permission/index.gsp
<html lang="en">

<head>
    <meta name="layout" content="layoutContent"/>
    <g:set var="entityName" value="${message(code: 'role.permission', default: 'Permission')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
</head>

<body>

<br/>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <g:message code="default.list.label" args="[entityName]" />
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                        <tr>
                            <th>${message(code: 'com.ef.qm.label.name',default: "Name")}</th>
                            <th>${message(code: 'com.ef.qm.label.description',default: "Description")}</th>
                            <th class="hidden"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <g:each in="${permissionInstanceList}" status="i" var="permissionInstance">
                            <tr class="${(i % 2) == 0 ? 'even gradeC' : 'odd gradeX'}">

                                <td>${permissionInstance?.name}</td>

                                <td>${fieldValue(bean: permissionInstance, field: "description")}</td>

                                <td></td>
                            </tr>
                        </g:each>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<script src="${resource(dir: 'theme/bower_components/jquery/dist/', file: 'jquery.min.js')}"></script>
<script src="${resource(dir: 'theme/bower_components/bootstrap/dist/js/', file: 'bootstrap.min.js')}"></script>
<script src="${resource(dir: 'theme/bower_components/metisMenu/dist/', file: 'metisMenu.min.js')}"></script>

<script src="${resource(dir: 'theme/bower_components/datatables/media/js/', file: 'jquery.dataTables.min.js')}"></script>
<script src="${resource(dir: 'theme/bower_components/datatables-plugins/integration/bootstrap/3/', file: 'dataTables.bootstrap.min.js')}"></script>

<script src="${resource(dir: 'theme/dist/js/', file: 'sb-admin-2.js')}"></script>
<script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
</script>

</body>

</html>