grails-app/domain/com/ef/app/qm/Questionnaire.groovy
package com.ef.app.qm

class Questionnaire {

	String questionnaireName

	boolean enable_q

	static hasMany = [questionnairegroups: Questionnairegroup]

	static mapping = {
		id column: "QUESTIONNAIRE_ID"
		version false
	}

	static constraints = {
		questionnaireName nullable: false
	}
}

grails-app/domain/com/ef/app/qm/Questionnairegroup.groovy
package com.ef.app.qm

class Questionnairegroup {

	String questionnairegroupName
	Integer questionnairegroupPonderation
	Questionnaire questionnaire
	String color
	String groupAndQuestionnaire

	static hasMany = [questionses: Questions]
	static belongsTo = [Questionnaire]
	static transients = ['groupAndQuestionnaire']

	static mapping = {
		id column: "QUESTIONNAIREGROUP_ID"
		version false
	}

	static constraints = {
		questionnairegroupName nullable: false
		questionnairegroupPonderation nullable: false
	}

	String getGroupAndQuestionnaire(){
		return questionnairegroupName+" :: "+questionnaire.questionnaireName
	}



}

grails-app/domain/com/ef/app/qm/Space.groovy
package com.ef.app.qm

class Space {
	String spaceCode
	String spaceName
	int spaceNumber
	String spaceAdress
	String spacePhone
	String spaceEmail
	String zone
	String region
	User user

	static hasMany = [planning: Planning]

	static belongsTo = [User]

	static mapping = {
		id column: "SPACE_ID"
		version false
		sort spaceName: "asc"
	}

	static constraints = {
		spaceCode nullable: true
		spaceName nullable: false
		spaceNumber nullable: false
		spaceAdress nullable: true
		spacePhone nullable: true
		spaceEmail nullable: true,email: true
		user nullable: true
		zone nullable: true
		region nullable: true
	}

	String toString(){
		return spaceName
	}
}

grails-app/controllers/com/ef/app/qm/QuestionnairegroupController.groovy
package com.ef.app.qm

import com.ef.app.qm.Questionnairegroup

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class QuestionnairegroupController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Questionnairegroup.list(params), model:[questionnairegroupInstanceCount: Questionnairegroup.count()]
    }

    def show(Questionnairegroup questionnairegroupInstance) {
        respond questionnairegroupInstance
    }

    def create() {
        respond new Questionnairegroup(params)
    }

    @Transactional
    def save(Questionnairegroup questionnairegroupInstance) {


        if (questionnairegroupInstance == null) {
            notFound()
            return
        }

        //render questionnairegroupInstance.hasErrors()
        //return

        if (questionnairegroupInstance.hasErrors()) {
            flash.type="danger"
            flash.message = message(code: 'default.null.message2')
            render view: 'create', model: [questionnairegroupInstance:questionnairegroupInstance]
            return
        }

        def listEvaluations = Evaluation.findAllByQuestionnaire(questionnairegroupInstance.questionnaire);

        if (listEvaluations.size()>0)
        {
            def  listGroup = Questionnairegroup.findAllByQuestionnaire(questionnairegroupInstance.questionnaire)

            def questionnaire = new Questionnaire();
            questionnaire.questionnaireName = "Espace TT "+((Questionnaire.list().size())+1)
            questionnaire.enable_q = false

            questionnaire.save flush:true

            for(quGroupe in listGroup)
            {

                def groupeQuestion = new Questionnairegroup();
                groupeQuestion.questionnaire=questionnaire
                groupeQuestion.color=quGroupe.color
                groupeQuestion.questionnairegroupName=quGroupe.questionnairegroupName
                groupeQuestion.questionnairegroupPonderation=quGroupe.questionnairegroupPonderation

                groupeQuestion.save flush:true

                def listQuestions = Questions.findAllByQuestionnairegroup(quGroupe)

                for(qs in listQuestions)
                {

                    def q = new Questions()

                    q.questionMaturity = qs.questionMaturity
                    q.questionnairegroup = Questionnairegroup.get(groupeQuestion.id)
                    q.questionName = qs.questionName
                    q.questionPoints = qs.questionPoints

                    q.save flush:true

                }
            }

            questionnairegroupInstance.questionnaire=questionnaire

        }

        questionnairegroupInstance.color="#"+questionnairegroupInstance.color

        questionnairegroupInstance.save flush:true


        request.withFormat {
            form multipartForm {
                flash.type="success"
                flash.message = message(code: 'default.created.message', args: [message(code: 'questionnaire.label', default: 'com.ef.app.qm.Questionnairegroup'), questionnairegroupInstance.id])
                redirect questionnairegroupInstance
            }
            '*' { respond questionnairegroupInstance, [status: CREATED] }
        }

    }

    def edit(Questionnairegroup questionnairegroupInstance) {
        respond questionnairegroupInstance
    }


    def update(Questionnairegroup questionnairegroupInstance) {

        if (questionnairegroupInstance == null)
            {
                notFound();
                return
            }

            if (questionnairegroupInstance.hasErrors()) {
                flash.type="danger"
                flash.message = message(code: 'default.null.message2')
                render view: 'edit', model: [questionnairegroupInstance:questionnairegroupInstance]
                return
            }

            def idf = questionnairegroupInstance.id;
            def listEvaluations = Evaluation.findAllByQuestionnaire(questionnairegroupInstance.questionnaire);

            if (listEvaluations.size() == 0)
            {
                questionnairegroupInstance.color="#"+questionnairegroupInstance.color
                questionnairegroupInstance.save flush:true

                idf = questionnairegroupInstance.id;
            }
            else
            {
                def questionnairegroupNameExist = params.questionnairegroupNameExist
                def questionnairegroupPonderationExist = params.questionnairegroupPonderationExist



                if (questionnairegroupNameExist != questionnairegroupInstance.questionnairegroupName ||
                        Integer.parseInt(""+questionnairegroupPonderationExist) != questionnairegroupInstance.questionnairegroupPonderation)
                {

                    def  listGroup = Questionnairegroup.findAllByQuestionnaire(questionnairegroupInstance.questionnaire)

                    def questionnaire = new Questionnaire();
                    questionnaire.questionnaireName = "Espace TT "+((Questionnaire.list().size())+1)
                    questionnaire.enable_q = false
                    questionnaire.save()

                    for(quGroupe in listGroup)
                    {
                        def groupeQuestion = new Questionnairegroup();
                        groupeQuestion.questionnaire=questionnaire
                        groupeQuestion.color="#"+quGroupe.color.replace('#','')
                        groupeQuestion.questionnairegroupName=quGroupe.questionnairegroupName
                        groupeQuestion.questionnairegroupPonderation=quGroupe.questionnairegroupPonderation
                        groupeQuestion.save()

                        def listQuestions = Questions.findAllByQuestionnairegroup(quGroupe)

                        for(qs in listQuestions)
                        {
                            def q = new Questions()
                            q.questionMaturity = qs.questionMaturity
                            q.questionnairegroup = groupeQuestion
                            q.questionName = qs.questionName
                            q.questionPoints = qs.questionPoints
                            q.na = qs.na
                            q.save()
                        }
                    }


                    idf = Questionnairegroup.findAllByQuestionnairegroupName(questionnairegroupInstance.questionnairegroupName).last().id


                }
                else
                {
                    questionnairegroupInstance.color="#"+questionnairegroupInstance.color

                    questionnairegroupInstance.save flush:true
                }
            }


            request.withFormat {
                form multipartForm {
                    flash.type="success"
                    flash.message = message(code: 'default.updated.message')
                    redirect(uri: "/questionnairegroup")
                }
                '*' { respond questionnairegroupInstance, [status: OK] }
            }
    }

    @Transactional
    def delete(Questionnairegroup questionnairegroupInstance) {
        if (questionnairegroupInstance == null) {
            notFound()
            return
        }

        def listEvaluations = Evaluation.findAllByQuestionnaire(questionnairegroupInstance.questionnaire);

        if (listEvaluations.size()>0)
        {
            def  listGroup = Questionnairegroup.findAllByQuestionnaire(questionnairegroupInstance.questionnaire)

            def questionnaire = new Questionnaire();
            questionnaire.questionnaireName = "Espace TT "+((Questionnaire.list().size())+1)
            questionnaire.enable_q = false

            questionnaire.save flush:true


            for(quGroupe in listGroup)
            {
                def groupeQuestion = new Questionnairegroup();
                groupeQuestion.questionnaire=questionnaire
                groupeQuestion.color=quGroupe.color
                groupeQuestion.questionnairegroupName=quGroupe.questionnairegroupName
                groupeQuestion.questionnairegroupPonderation=quGroupe.questionnairegroupPonderation

                groupeQuestion.save flush:true

                def listQuestions = Questions.findAllByQuestionnairegroup(quGroupe)

                for(qs in listQuestions)
                {
                    def q = new Questions()

                    q.questionMaturity = qs.questionMaturity
                    q.questionnairegroup = qs.questionnairegroup
                    q.questionName = qs.questionName
                    q.questionPoints = qs.questionPoints

                    q.save flush:true
                }
            }
        }
        else
        {
            questionnairegroupInstance.delete flush:true
        }


        request.withFormat {
            form multipartForm {
                flash.type="success"
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'com.ef.app.qm.Questionnairegroup.label', default: 'com.ef.app.qm.Questionnairegroup'), questionnairegroupInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'questionnairegroup.label', default: 'com.ef.app.qm.Questionnairegroup'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/questionnairegroup/_form.gsp
<%@ page import="com.ef.app.qm.Questionnaire" %>

<div class="row form-group has-${hasErrors(bean: questionnairegroupInstance, field: 'questionnairegroupName', 'error')}">
	<div class="col-lg-3" style="font-weight: bold" >
		<g:message code="questionnairegroup.name.label" default="Questionnaire Name" />
		<span class="required-indicator" style="color:red" >*</span>
	</div>
	<div class="col-lg-3">
		<g:textField  class="form-control" name="questionnairegroupName" value="${questionnairegroupInstance?.questionnairegroupName}"/>

	</div>
</div>


<div class="row form-group has-${hasErrors(bean: questionnairegroupInstance, field: 'questionnairegroupPonderation', 'error')}">
	<div class="col-lg-3" style="font-weight: bold" >
		<g:message code="questionnairegroup.ponderation.label" default="Questionnairegroup Ponderation" />
		<span class="required-indicator" style="color:red" >*</span>
	</div>
	<div class="col-lg-3">
		<g:textField  class="form-control" name="questionnairegroupPonderation" value="${questionnairegroupInstance?.questionnairegroupPonderation}"/>

	</div>
</div>

<div class="row form-group ">
	<div class="col-lg-3" style="font-weight: bold" >

		<g:message code="questionnairegroup.color.label" default="Couleur" />
		<span class="required-indicator" style="color:red" >*</span>
	</div>
	<div class="col-lg-3">
		<g:textField  class="jscolor form-control" name="color" value="${(questionnairegroupInstance?.color == null)?'337ab7':questionnairegroupInstance?.color}"/>
	</div>
</div>


<div class="row form-group has-${hasErrors(bean: questionnairegroupInstance, field: 'questionnaire', 'error')}">
	<div class="col-lg-3" style="font-weight: bold" >
		<g:message code="questionnairegroup.questionnaire.label" default="Questionnaire" />
		<span class="required-indicator" style="color:red" >*</span>
	</div>
	<div class="col-lg-3">
		<g:select class="form-control" value="${spaceInstance?.user?.id}" id="questionnaire" name="questionnaire.id" from="${com.ef.app.qm.Questionnaire.list()}" optionKey="id" optionValue="questionnaireName" />
	</div>
</div>

grails-app/views/questionnairegroup/create.gsp
<html lang="en">

<head>
	<meta name="layout" content="layoutContent"/>
	<g:set var="entityName" value="${message(code: 'questionnairegroup.label', default: 'Questionnairegroup')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>

<br/>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<g:message code="questionnairegroup.label" />
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="row" style="padding-bottom: 20px">
					<div class="col-lg-3" role="navigation">
						<g:link class="btn btn-primary btn-block" action="index"><g:message code="questionnairegroup.label.list" /></g:link>
					</div>
				</div>
				<div id="create-questionnairegroup" class="content scaffold-create" role="main">

					<g:form url="[resource:questionnairegroupInstance, action:'save']" >
						<fieldset class="form">
							<g:render template="form"/>
						</fieldset>
						<fieldset class="buttons">
							<br/>
							<g:submitButton name="create" class="btn btn-success" value="${message(code: 'default.button.create.label', default: 'Create')}" />
						</fieldset>
					</g:form>
				</div>

			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>


</body>

<script >

	$(function(){
		$(".ponderation").keyup(function(){
			if(!$(this).val().match(/^\d+$/) || parseInt($(this).val(),10)>100 || parseInt($(this).val(),10)<0 ){
				$(this).val("");
			}
		});
	});

</script>

</html>

grails-app/views/questionnairegroup/edit.gsp
<html lang="en">

<head>
	<meta name="layout" content="layoutContent"/>
	<g:set var="entityName" value="${message(code: 'questionnairegroup.label', default: 'Questionnairegroup')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>

<br/>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<g:message code="questionnairegroup.label" />
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="row" style="padding-bottom: 20px">
					<div class="col-lg-3" role="navigation">
						<g:link class="btn btn-primary btn-block" action="index"><g:message code="questionnairegroup.label.list"  /></g:link>
					</div>
					<div class="col-lg-3" role="navigation">
						<g:link class="btn btn-primary btn-block" action="create"><g:message code="questionnairegroup.label.new" /></g:link></div>
				</div>
				<div id="edit-questionnairegroup" class="content scaffold-edit" role="main">
					<g:form url="[resource:questionnairegroupInstance, action:'update']" method="PUT" >
						<g:hiddenField name="version" value="${questionnairegroupInstance?.version}" />
						<fieldset class="form">
							<div class="row form-group has-${hasErrors(bean: questionnairegroupInstance, field: 'questionnairegroupName', 'error')}">
								<div class="col-lg-3" style="font-weight: bold" >
									<g:message code="questionnairegroup.name.label" default="Questionnaire Name" />
									<span class="required-indicator" style="color:red" >*</span>
								</div>
								<div class="col-lg-3">
									<g:textField  class="form-control" name="questionnairegroupName" value="${questionnairegroupInstance?.questionnairegroupName}"/>
								</div>
							</div>


							<div class="row form-group has-${hasErrors(bean: questionnairegroupInstance, field: 'questionnairegroupPonderation', 'error')}">
								<div class="col-lg-3" style="font-weight: bold" >
									<g:message code="questionnairegroup.ponderation.label" default="Questionnairegroup Ponderation" />
									<span class="required-indicator" style="color:red" >*</span>
								</div>
								<div class="col-lg-3">
									<g:textField  class="form-control" name="questionnairegroupPonderation" value="${questionnairegroupInstance?.questionnairegroupPonderation}"/>
								</div>
							</div>

							<div class="row form-group ">
								<div class="col-lg-3" style="font-weight: bold" >

									<g:message code="questionnairegroup.color.label" default="Couleur" />
									<span class="required-indicator" style="color:red" >*</span>
								</div>
								<div class="col-lg-3">
									<g:textField  class="jscolor form-control" name="color" value="${questionnairegroupInstance?.color}"/>
									<g:hiddenField name="questionnaire" value="${questionnairegroupInstance?.questionnaire?.id}"/>
									<g:hiddenField  class="form-control" name="questionnairegroupNameExist" value="${questionnairegroupInstance?.questionnairegroupName}"/>
									<g:hiddenField  class="form-control" name="questionnairegroupPonderationExist" value="${questionnairegroupInstance?.questionnairegroupPonderation}"/>
								</div>
							</div>
						</fieldset>
						<fieldset class="buttons">
							<br/>
							<g:actionSubmit class="btn btn-success" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />

						</fieldset>
					</g:form>


				</div>

			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>

</body>

</html>

grails-app/views/questionnairegroup/index.gsp
<%@ page import="com.ef.app.qm.User_holidays" %>

<html lang="en">

<head>
	<meta name="layout" content="layoutContent"/>
	<g:set var="entityName" value="${message(code: 'questionnairegroup.label', default: 'Questionnairegroup')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>

<body>

<br/>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				${message(code: 'questionnairegroup.label.list' )}
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="col-lg-3" role="main">
					<g:link class="btn btn-primary btn-block" action="create">${message(code: 'questionnairegroup.label.new')}</g:link>
					<br/>
				</div>
				<div class="dataTable_wrapper">
					<table class="table table-striped table-bordered table-hover" id="dataTables-example">
						<thead>
						<tr>
							<th>${message(code: 'questionnairegroup.name.label')}</th>
							<th>${message(code: 'questionnairegroup.ponderation.label')}</th>
							<th>${message(code: 'questionnairegroup.questionnaire.label')}</th>
						</tr>
						</thead>
						<tbody>

						<g:each in="${com.ef.app.qm.Questionnairegroup.list()}" status="i" var="questionnairegroupInstance">
							<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

								<td><g:link action="show" id="${questionnairegroupInstance.id}">
									${fieldValue(bean: questionnairegroupInstance, field: "questionnairegroupName")}</g:link></td>

								<td>${fieldValue(bean: questionnairegroupInstance, field: "questionnairegroupPonderation")}</td>

								<td>${questionnairegroupInstance?.questionnaire?.questionnaireName}</td>

							</tr>
						</g:each>

						</tbody>
					</table>
				</div>
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>

<script>
	$(document).ready(function() {
		$('#dataTables-example').DataTable({
			responsive: true,
			"order": [[ 2, "asc" ]]
		});


	});
</script>

</body>

</html>

grails-app/views/questionnairegroup/show.gsp
<html lang="en">

<head>
	<meta name="layout" content="layoutContent"/>
	<g:set var="entityName" value="${message(code: 'questionnairegroup.label', default: 'Questionnairegroup')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>

<br/>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<g:message code="questionnairegroup.label.show" />
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="row" style="padding-bottom: 20px">
					<div class="col-lg-3" role="navigation">
						<g:link class="btn btn-primary btn-block" action="index"><g:message code="questionnairegroup.label.list" /></g:link>
					</div>
					<div class="col-lg-3" role="navigation">
						<g:link class="btn btn-primary btn-block" action="create"><g:message code="questionnairegroup.label.new"  /></g:link></div>
				</div>
				<div id="show-questionnairegroup" class="content scaffold-show" role="main">

%{--					<g:if test="${questionnaireInstance?.questionnaireName}">
						<div class="row form-group">
							<div class="col-lg-3" style="font-weight: bold;padding-top: 8px;" >
								<g:message code="questionnaire.questionnaireName.label" default="Questionnaire Name" />
							</div>
							<div class="col-lg-3">
								<pre><g:fieldValue bean="${questionnaireInstance}" field="questionnaireName"/></pre>
							</div>
						</div>
					</g:if>

					<g:if test="${questionnaireInstance?.questionnairegroups}">
						<div class="row form-group">
							<div class="col-lg-3" style="font-weight: bold;padding-top: 8px;" >
								<g:message code="questionnaire.questionnairegroups.label" default="Questionnairegroups" />
							</div>
							<div class="col-lg-3">
								<g:each in="${questionnaireInstance.questionnairegroups}" var="q">
									<span class="property-value" aria-labelledby="questionnairegroups-label"><g:link controller="questionnairegroup" action="show" id="${q.id}">${q.questionnairegroupName}</g:link></span><br/><br/>
								</g:each>
							</div>
						</div>
					</g:if>--}%

					<g:if test="${questionnairegroupInstance?.questionnairegroupName}">
						<div class="row form-group">
							<div class="col-lg-3" style="font-weight: bold;padding-top: 8px;" >
								<g:message code="questionnairegroup.name.label" default="Nom du groupe questions" />
							</div>
							<div class="col-lg-4">
								<pre><g:fieldValue bean="${questionnairegroupInstance}" field="questionnairegroupName"/></pre>
							</div>
						</div>
					</g:if>

					<g:if test="${questionnairegroupInstance?.questionnairegroupPonderation}">
						<div class="row form-group">
							<div class="col-lg-3" style="font-weight: bold;padding-top: 8px;" >
								<g:message code="questionnairegroup.ponderation.label" default="Ponderation" />
							</div>
							<div class="col-lg-4">
								<pre><g:fieldValue bean="${questionnairegroupInstance}" field="questionnairegroupPonderation"/></pre>
							</div>
						</div>
					</g:if>

					<g:if test="${questionnairegroupInstance?.questionnaire}">
						<div class="row form-group">
							<div class="col-lg-3" style="font-weight: bold;padding-top: 8px;" >
								<g:message code="questionnairegroup.questionnaire.label" default="Ponderation" />
							</div>
							<div class="col-lg-4">
								<pre><g:link controller="questionnaire" action="show" id="${questionnairegroupInstance?.questionnaire?.id}">${questionnairegroupInstance?.questionnaire?.questionnaireName}</g:link></pre>
							</div>
						</div>
					</g:if>

					<g:if test="${questionnairegroupInstance.color}">
						<div class="row form-group">
							<div class="col-lg-3" style="font-weight: bold;padding-top: 8px;" >
								<g:message code="questionnairegroup.color.label" default="Ponderation" />
							</div>
							<div class="col-lg-4">
								<pre style="background-color: #${questionnairegroupInstance.color}" ><g:fieldValue bean="${questionnairegroupInstance}" field="color"/></pre>
							</div>
						</div>
					</g:if>

					<g:if test="${questionnairegroupInstance?.questionses}">

						<div class="row form-group">
							<div class="col-lg-3" style="font-weight: bold;padding-top: 8px;" >
								<g:message code="questionnairegroup.questions.label" default="Questions" />
							</div>
							<div class="col-lg-4">
								<g:each in="${questionnairegroupInstance.questionses}" var="q">
								<li><g:link controller="questions" action="show" id="${q.id}">${q?.questionName}</g:link></li>
								</g:each>
							</div>
						</div>

					</g:if>

				</div>

				<div class="row" style="padding-top: 20px">
					<g:form url="[resource:questionnairegroupInstance, action:'delete']" method="DELETE">
						<div class="col-lg-2" role="navigation">
							<g:link class="btn btn-success btn-block" action="edit" resource="${questionnairegroupInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
						</div>
%{--						<div class="col-lg-2" role="navigation">
							<g:actionSubmit class="btn btn-danger btn-block" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
						</div>--}%
					</g:form>

				</div>

			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>

</body>

</html>